version: '3.4'

services:
  userdb:
    image: postgres
    container_name: userdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=userdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    container_name: user.api
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:UserDBConnection=Server=userdb;Port=5432;Database=userdb;User Id=admin;Password=admin1234;" 
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  clr-portal:
    container_name: clr-portal
    build:
      context: ./WebApps/clr-portal
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - './src:/app/src' 

volumes:
  postgres_data:
  pgadmin_data: