version: '3.4'

services:
  userdb:
    image: postgres
    container_name: userdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=userdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/  

  user.api:
    image: 654654428833.dkr.ecr.ap-south-1.amazonaws.com/clr:userapi-latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:UserDBConnection=Server=userdb;Port=5432;Database=userdb;User Id=admin;Password=admin1234;" 
    ports:
      - "80"
    depends_on:
      - userdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_data: